import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, BarChart3, Check, ChevronRight, ClipboardCheck, Database, FileSearch, Gauge, LineChart, LockKeyhole, MousePointerClick, Network, Search, Server, Settings2, ShieldCheck, ShoppingCart, Tags, Target, Workflow } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Analytics & Tracking Services | GA4, GTM, Conversion Tracking & Attribution',
  description: 'Analytics and tracking services covering GA4, Google Tag Manager, conversion tracking, attribution, CRM integration, ecommerce measurement and marketing dashboards.',
  alternates: { canonical: 'https://rominelabs.com/services/analytics-tracking' },
  openGraph: { title: 'Analytics & Tracking Services | Romine Labs', description: 'Build a reliable measurement system for your website, marketing channels, conversions, attribution and CRM.', url: 'https://rominelabs.com/services/analytics-tracking', type: 'website' },
  twitter: { card: 'summary_large_image', title: 'Analytics & Tracking Services | Romine Labs', description: 'GA4, GTM, conversion tracking, attribution, CRM integration and marketing analytics built around business decisions.' },
}

const services = [
  ['GA4 Implementation','Configure Google Analytics 4 around business questions, events, conversions, audiences and reporting needs.',LineChart],
  ['Google Tag Manager','Build a structured tag-management layer for tags, triggers, variables, custom events, testing and maintenance.',Tags],
  ['Conversion Tracking','Measure leads, purchases, bookings, calls, signups, demos, enquiries and other meaningful outcomes.',Target],
  ['Event Tracking','Design useful event architecture for CTA clicks, forms, product views, checkout, downloads and engagement.',MousePointerClick],
  ['Marketing Attribution','Create a practical framework for source, medium, campaign, first-touch, last-touch, platform and CRM attribution.',Network],
  ['CRM & Revenue Integration','Connect marketing activity to leads, opportunities, customers and revenue where the technology stack supports it.',Database],
  ['Paid Advertising Tracking','Configure measurement for Google Ads, Meta, TikTok, LinkedIn and other relevant advertising channels.',Gauge],
  ['E-commerce Tracking','Measure product discovery, carts, checkout, purchases, revenue, product attributes and funnel behavior.',ShoppingCart],
  ['Call & Form Tracking','Measure phone interactions and form journeys, including source and abandonment signals where technically feasible.',MousePointerClick],
  ['Analytics Audits','Find missing events, duplicate tags, broken conversions, attribution problems, UTM issues and data-quality risks.',FileSearch],
] as const

const measurement = [
  ['01','Business objective','What is the organization trying to achieve?'],
  ['02','KPI','Which metric best represents progress toward that objective?'],
  ['03','Conversion','Which completed action represents meaningful business value?'],
  ['04','Event','Which interactions lead users toward that conversion?'],
  ['05','Data source','Where should the signal originate and how should it be validated?'],
  ['06','Reporting','How will the information become a useful management decision?'],
] as const

const process = [
  ['01','Discovery','Understand objectives, website architecture, marketing channels, CRM and existing measurement.'],
  ['02','Measurement Audit','Inspect gaps, duplication, broken events, attribution issues and data-quality risks.'],
  ['03','KPI Definition','Define metrics and conversions that matter to the business model.'],
  ['04','Measurement Plan','Map goals to events, parameters, conversions, platforms and reporting.'],
  ['05','Implementation','Configure GA4, GTM, pixels, conversion signals, ecommerce events and required layers.'],
  ['06','Integration','Connect advertising platforms, CRM systems and relevant data sources where practical.'],
  ['07','QA & Validation','Test events, tags, parameters, consent behavior, UTMs, forms, ecommerce and cross-domain journeys.'],
  ['08','Reporting & Optimization','Turn reliable data into reporting, findings and prioritized improvements.'],
] as const

const faqs = [
 ['What is digital analytics?','Digital analytics is the process of collecting, organizing, analyzing and interpreting digital behavior and marketing data so a business can understand performance and make better decisions.'],
 ['What is GA4?','Google Analytics 4 is Google’s current analytics platform for measuring interactions across websites and apps using an event-based data model.'],
 ['What is Google Tag Manager?','Google Tag Manager is a tag-management system that helps teams deploy and maintain analytics, advertising and other tracking tags through a controlled interface instead of scattering scripts throughout website code.'],
 ['What is analytics tracking?','Analytics tracking is the technical implementation that records selected user interactions, events, conversions and marketing signals so they can be analyzed later.'],
 ['What should a business track?','Track the interactions and outcomes that answer important commercial questions: acquisition, engagement, leads, purchases, bookings, signups, revenue and meaningful funnel steps.'],
 ['What is conversion tracking?','Conversion tracking measures a defined action that represents meaningful progress or business value, such as a purchase, qualified lead, booking, signup or quote request.'],
 ['What is event tracking?','Event tracking records a specific interaction, such as a CTA click, form start, product view, add-to-cart action or download. Events should support a measurement strategy rather than be collected indiscriminately.'],
 ['Why is my analytics data inaccurate?','Common causes include duplicate tags, missing events, incorrect conversion configuration, self-referrals, internal traffic, inconsistent UTMs, cross-domain issues, consent behavior and timezone differences.'],
 ['Why do Google Ads and GA4 numbers not match?','Google Ads and GA4 can use different attribution, reporting windows, conversion definitions and processing rules. Different totals do not automatically mean one system is broken.'],
 ['Why do Meta and Google report different conversions?','Advertising platforms can assign credit using their own attribution methodologies and reporting windows, so their totals may differ from GA4 and each other.'],
 ['What is attribution?','Attribution is the process of assigning credit or analytical context to marketing touchpoints associated with a conversion. Common approaches include first touch, last touch, multi-touch, platform and CRM attribution.'],
 ['What are UTM parameters?','UTM parameters are campaign-tracking values added to URLs so analytics systems can identify source, medium, campaign and related context. Consistent naming is essential.'],
 ['Do I need Google Tag Manager?','Not every business requires GTM. It becomes especially useful when multiple analytics and advertising tags, events or conversion signals need structured management.'],
 ['Can you set up GA4?','Yes. A GA4 implementation can include property configuration, data streams, event design, conversions, audiences, custom dimensions or metrics where appropriate, debugging and validation.'],
 ['Can you fix broken tracking?','Yes. An analytics audit can identify missing, duplicated, incorrectly configured or technically broken tracking and establish a remediation plan.'],
 ['Can you track form submissions?','Yes. Forms can be measured across views, starts and successful submissions, with abandonment signals where technically feasible.'],
 ['Can you track phone calls?','Yes. Website phone clicks can be tracked directly. Full call-source and outcome measurement may require a dedicated call-tracking or telephony integration.'],
 ['Can you track purchases?','Yes. Ecommerce implementations can measure product views, carts, checkout, purchases, revenue and other supported commerce details.'],
 ['Can you connect analytics to my CRM?','Potentially, depending on the CRM and technical stack. Common systems include HubSpot, Salesforce, Zoho and Pipedrive.'],
 ['Can you track leads through the sales process?','Where the CRM exposes reliable data, marketing sources can be connected to lead, opportunity and customer stages, creating a stronger view than form submissions alone.'],
 ['Can you build a marketing dashboard?','Yes. Depending on the engagement, reporting can combine GA4, Search Console, advertising platforms, CRM information and other sources into a focused dashboard.'],
 ['Can you track Google Ads conversions?','Yes. Conversion measurement can be configured using the appropriate Google Ads and analytics architecture, depending on the site, consent requirements and conversion type.'],
 ['Can you track Meta Ads?','Yes. Meta Pixel and, where appropriate, Conversions API can be implemented according to the website architecture, consent model and current platform capabilities.'],
 ['Can you track TikTok Ads?','Yes, where TikTok measurement capabilities fit the project. Browser events and supported server-side approaches can be considered.'],
 ['Can you track LinkedIn Ads?','Yes. LinkedIn campaign and conversion measurement can be configured where the audience, objectives and technical environment make it appropriate.'],
 ['Can you implement server-side tracking?','Server-side or API-based measurement can be considered where it solves a real measurement need. It is not a universal replacement for browser-side measurement and must account for consent and platform requirements.'],
 ['Is analytics compliant with privacy laws?','Compliance depends on the organization, jurisdictions, data practices and configuration. We can implement privacy-aware measurement, but legal determinations should be made with qualified legal or privacy advisers.'],
 ['Do I need a cookie consent system?','If your data practices and jurisdictions require consent controls, an appropriate consent-management approach may be necessary. A banner alone does not guarantee compliance.'],
 ['Can you audit my current analytics?','Yes. An audit can review tracking, conversions, tags, attribution, website interactions, advertising signals, CRM continuity and reporting quality.'],
 ['Can analytics help improve SEO?','Yes. Analytics can connect organic search traffic with landing-page behavior and business outcomes. Search Console adds query and visibility data that GA4 does not provide.'],
 ['Can analytics improve paid advertising?','Yes. Reliable conversion signals help teams evaluate campaigns using qualified leads, purchases, revenue, acquisition cost and return rather than clicks alone.'],
 ['How long does analytics implementation take?','Timing depends on website complexity, platforms, event count, ecommerce, CRM integration, consent architecture, domains and existing implementation quality.'],
 ['What happens after tracking is installed?','Implementation is followed by QA, validation, documentation and reporting. Tracking should become a maintained measurement system, not a one-time installation.'],
]

const jsonLd = {
  '@context':'https://schema.org','@graph':[
    {'@type':'Organization',name:'Romine Labs',url:'https://rominelabs.com'},
    {'@type':'WebPage',name:'Analytics & Tracking Services',url:'https://rominelabs.com/services/analytics-tracking',description:metadata.description},
    {'@type':'Service',name:'Analytics & Tracking Services',serviceType:'Digital Analytics, Tracking, Attribution and Measurement',provider:{'@type':'Organization',name:'Romine Labs',url:'https://rominelabs.com'},areaServed:'Worldwide',url:'https://rominelabs.com/services/analytics-tracking'},
    {'@type':'BreadcrumbList',itemListElement:[
      {'@type':'ListItem',position:1,name:'Home',item:'https://rominelabs.com/'},
      {'@type':'ListItem',position:2,name:'Services',item:'https://rominelabs.com/services'},
      {'@type':'ListItem',position:3,name:'Analytics & Tracking',item:'https://rominelabs.com/services/analytics-tracking'},
    ]},
    {'@type':'FAQPage',mainEntity:faqs.map(([name,text])=>({'@type':'Question',name,acceptedAnswer:{'@type':'Answer',text}}))},
  ]
}

function Label({children}:{children:React.ReactNode}) { return <p className="text-xs font-bold uppercase tracking-[.2em] text-brand">{children}</p> }
function Heading({label,title,children}:{label:string;title:string;children?:React.ReactNode}) { return <div className="max-w-4xl"><Label>{label}</Label><h2 className="mt-4 text-4xl font-black tracking-[-.035em] sm:text-5xl lg:text-6xl">{title}</h2>{children&&<p className="mt-6 text-lg leading-8 text-muted-foreground">{children}</p>}</div> }
function ArrowLink({href,children}:{href:string;children:React.ReactNode}) { return <Link href={href} className="group inline-flex items-center gap-2 text-sm font-bold underline decoration-border underline-offset-4 hover:text-brand hover:decoration-brand">{children}<ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></Link> }

export default function AnalyticsTrackingPage() {
 return <>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}} />
  <main className="overflow-x-hidden bg-background text-foreground">
   <section data-hero-dark className="relative min-h-[55vh] overflow-hidden bg-slate-950 text-white">
    <Image src="/images/hero-data.png" alt="Analytics and digital marketing data environment with performance visualizations" fill priority sizes="100vw" className="object-cover object-center opacity-40" />
    <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(2,6,23,.98)_0%,rgba(2,6,23,.84)_48%,rgba(2,6,23,.42)_100%)]"/><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(2,6,23,1)_0%,transparent_45%,rgba(2,6,23,.5)_100%)]"/>
    <div className="relative mx-auto flex min-h-[55vh] max-w-7xl items-center px-5 pb-16 pt-28 sm:px-8 lg:px-12"><div className="max-w-4xl">
      <div className="mb-6 inline-flex items-center gap-2 border border-white/15 bg-white/5 px-4 py-2 text-xs font-semibold uppercase tracking-[.18em] text-white/80"><BarChart3 className="size-3.5 text-brand"/> Analytics & Tracking</div>
      <h1 className="max-w-4xl text-5xl font-black leading-[.98] tracking-[-.05em] sm:text-6xl lg:text-8xl">Know what&apos;s working. <span className="text-brand">Measure what matters.</span></h1>
      <p className="mt-7 max-w-2xl text-base leading-7 text-slate-300 sm:text-xl sm:leading-8">We build reliable analytics, tracking, attribution and reporting systems that connect marketing activity with the business outcomes behind it.</p>
      <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/contact" className="inline-flex items-center justify-center gap-2 bg-brand px-7 py-4 text-sm font-bold text-white hover:bg-brand/90">Fix My Tracking <ArrowRight className="size-4"/></Link><Link href="/contact" className="inline-flex items-center justify-center gap-2 border border-white/20 bg-white/5 px-7 py-4 text-sm font-bold text-white hover:bg-white/10">Book a Consultation</Link></div>
    </div></div>
   </section>

   <section className="border-b border-border py-20 lg:py-28"><div className="mx-auto grid max-w-7xl gap-14 px-5 sm:px-8 lg:grid-cols-12 lg:px-12"><div className="lg:col-span-5"><Heading label="The measurement problem" title="If you can&apos;t measure it reliably, you can&apos;t optimize it."/></div><div className="lg:col-span-7"><p className="text-lg leading-8 text-muted-foreground">Most businesses do not have a shortage of data. They have a shortage of trustworthy measurement. Numbers live in GA4, ad platforms, forms, spreadsheets and CRMs, but nobody is confident that the pieces describe the same customer journey.</p><div className="mt-9 grid gap-3 sm:grid-cols-2">{['Traffic numbers do not match across platforms.','Leads are submitted but their sources are unclear.','Forms and phone interactions are not consistently measured.','Duplicate or missing conversions distort campaign decisions.','UTM parameters are inconsistent across campaigns.','CRM outcomes never make it back into marketing analysis.','Analytics is installed, but nobody trusts the reports.','Platform-reported conversions are treated as ground truth without context.'].map(x=><div key={x} className="flex gap-3 border-t border-border py-3 text-sm leading-6"><Check className="mt-1 size-4 shrink-0 text-brand"/>{x}</div>)}</div><div className="mt-9 border-l-2 border-brand pl-5 text-sm leading-7 text-muted-foreground">The objective is not to collect every possible data point. It is to collect the right signals, define them clearly, validate them and turn them into decisions.</div></div></div></section>

   <section className="bg-muted/30 py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><Heading label="The fundamentals" title="What is digital analytics?"><strong>Digital analytics</strong> is the process of collecting, organizing, analyzing and interpreting digital behavior and marketing data to understand performance and make better decisions.</Heading><div className="mt-14 grid gap-px border border-border bg-border lg:grid-cols-6">{[['User interaction','A visitor takes an action.'],['Event','The meaningful action is recorded.'],['Data','The signal becomes available for analysis.'],['Insight','Patterns become visible.'],['Decision','The business chooses what to change.'],['Optimization','The next action is tested or implemented.']].map(([a,b])=><div key={a} className="bg-background p-6"><p className="font-black">{a}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{b}</p></div>)}</div><div className="mt-14 grid gap-12 lg:grid-cols-2"><div><h3 className="text-2xl font-black">What is tracking?</h3><p className="mt-4 leading-7 text-muted-foreground">Tracking is the implementation layer that records selected actions: page views, CTA clicks, form submissions, calls, downloads, product views, carts, checkout, purchases, signups, bookings and other meaningful interactions.</p></div><div><h3 className="text-2xl font-black">Data is not the same as insight.</h3><p className="mt-4 leading-7 text-muted-foreground">Data tells you what happened. Analytics helps investigate why it happened, where the signal came from, how confident you can be in it and what the business should do next.</p></div></div></div></section>

   <section className="py-20 lg:py-28"><div className="mx-auto grid max-w-7xl gap-14 px-5 sm:px-8 lg:grid-cols-12 lg:px-12"><div className="lg:col-span-5"><Heading label="Data quality" title="Bad data creates bad decisions.">A tag firing is not proof that a measurement system is correct. Reliable analytics requires architecture, naming, validation, consent handling and ongoing QA.</Heading></div><div className="lg:col-span-7"><div className="divide-y divide-border border-y border-border">{[['Duplicate events','The same interaction is sent more than once.'],['Missing conversions','Important business actions are not recorded correctly.'],['Self-referrals','Traffic is incorrectly attributed to the site itself.'],['UTM problems','Campaign parameters are inconsistent or overwritten.'],['Cross-domain issues','A journey across domains loses continuity.'],['Double-counted purchases','The same transaction is recorded more than once.'],['Timezone mismatches','Reports are compared using different reporting periods.'],['Consent behavior','Tags do not behave correctly under privacy choices.']].map(([a,b],i)=><div key={a} className="grid gap-4 py-6 sm:grid-cols-[70px_180px_1fr]"><span className="font-mono text-xs text-muted-foreground">0{i+1}</span><p className="font-bold">{a}</p><p className="text-sm leading-6 text-muted-foreground">{b}</p></div>)}</div><Link href="/contact" className="mt-8 inline-flex items-center gap-2 bg-foreground px-6 py-3 text-sm font-bold text-background">Find My Tracking Issues <ArrowRight className="size-4"/></Link></div></div></section>

   <section id="services" className="border-y border-border bg-muted/30 py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><Heading label="What we implement" title="Analytics & tracking services built around your measurement needs.">Implementation depends on your business model, website, marketing channels, CRM, conversion paths and existing data quality. There is no useful one-size-fits-all tracking package.</Heading><div className="mt-14 grid gap-px border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">{services.map(([title,text,Icon])=><article key={title} className="bg-background p-7"><Icon className="size-5 text-brand"/><h3 className="mt-6 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div><Link href="/contact" className="mt-10 inline-flex items-center gap-2 text-sm font-bold text-brand">Audit My Analytics <ArrowRight className="size-4"/></Link></div></section>

   <section id="measurement-strategy" className="py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><Heading label="Measurement strategy" title="Before we track anything, we define what matters.">A measurement system starts with business objectives, not a list of tags. We map the outcomes you care about to the signals, systems and reports needed to understand progress.</Heading><div className="mt-14 border-y border-border">{measurement.map(([n,a,b])=><div key={n} className="grid gap-5 border-b border-border py-7 last:border-0 md:grid-cols-[70px_220px_1fr]"><span className="font-mono text-sm text-brand">{n}</span><h3 className="font-black">{a}</h3><p className="text-sm leading-6 text-muted-foreground">{b}</p></div>)}</div><div className="mt-14 grid gap-8 lg:grid-cols-2"><div className="border border-border p-7"><p className="font-mono text-xs uppercase tracking-[.16em] text-brand">Measurement plan</p><h3 className="mt-3 text-2xl font-black">A practical map from goal to report.</h3><p className="mt-4 text-sm leading-6 text-muted-foreground">A measurement plan documents what should be measured, where it comes from, how it is named and how the resulting signal will be used.</p></div><div className="overflow-x-auto border border-border"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b border-border bg-muted/40">{['Business goal','KPI','Event','Platform'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{[['Generate leads','Qualified leads','generate_lead','GA4 / CRM'],['Sell products','Revenue','purchase','GA4 / Ads'],['Get bookings','Bookings','booking_complete','GA4 / CRM'],['Increase enquiries','Enquiries','form_submit','GA4']].map(r=><tr key={r[0]} className="border-b border-border last:border-0">{r.map(x=><td key={x} className="px-4 py-4">{x}</td>)}</tr>)}</tbody></table></div></div><div className="mt-10 border-l-2 border-brand pl-5 text-sm leading-7 text-muted-foreground">Event names such as <code>page_view</code>, <code>view_item</code>, <code>add_to_cart</code>, <code>begin_checkout</code>, <code>purchase</code>, <code>generate_lead</code>, <code>form_start</code> and <code>form_submit</code> can provide useful conventions, but naming should be adapted to the actual implementation and platform requirements.</div><Link href="/contact" className="mt-8 inline-flex items-center gap-2 bg-brand px-6 py-3 text-sm font-bold text-white">Build My Measurement Plan <ArrowRight className="size-4"/></Link></div></section>

   <section className="bg-slate-950 py-20 text-white lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><div className="grid gap-14 lg:grid-cols-12"><div className="lg:col-span-5"><Label>Conversion architecture</Label><h2 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">Connect the interaction to the revenue story.</h2><p className="mt-6 text-lg leading-8 text-slate-300">The useful question is not simply whether someone clicked. It is whether the interaction can be connected, with appropriate confidence, to a meaningful business outcome.</p></div><div className="lg:col-span-7"><div className="grid gap-3">{[['User','A person arrives from search, social, advertising, email or another source.'],['Interaction','The person views, clicks, starts, submits, purchases or completes another action.'],['Event','The selected interaction is recorded with appropriate parameters.'],['Conversion','A defined action represents meaningful progress or value.'],['Marketing source','Source, medium, campaign and available acquisition context are preserved.'],['CRM','Where integrated, the journey continues beyond the website.'],['Revenue','Business outcomes provide a stronger basis for investment decisions.']].map(([a,b],i)=><div key={a} className="border border-white/10 bg-white/[.03] p-5"><div className="flex gap-4"><span className="font-mono text-xs text-brand">0{i+1}</span><div><h3 className="font-black">{a}</h3><p className="mt-1 text-sm leading-6 text-slate-400">{b}</p></div></div></div>)}</div></div></div></div></section>

   <section className="py-20 lg:py-28"><div className="mx-auto grid max-w-7xl gap-16 px-5 sm:px-8 lg:grid-cols-12 lg:px-12"><div className="lg:col-span-7"><Heading label="Attribution" title="Where did the result come from?">Attribution helps assign analytical context or credit to marketing touchpoints. It is useful, but it is not a perfect reconstruction of reality.</Heading><div className="mt-10 grid gap-px border border-border bg-border sm:grid-cols-2">{[['First touch','Focuses on the first known interaction.'],['Last touch','Focuses on the final known interaction.'],['Multi-touch','Attempts to distribute credit across interactions.'],['Platform attribution','Uses an advertising platform’s methodology.'],['CRM attribution','Uses lead, opportunity and customer information.'],['Practical framework','Uses available signals and consistent definitions without pretending the data is perfect.']].map(([a,b])=><div key={a} className="bg-background p-6"><h3 className="font-black">{a}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{b}</p></div>)}</div></div><div className="lg:col-span-5"><div className="border border-border bg-muted/20 p-7"><Database className="size-6 text-brand"/><h3 className="mt-6 text-2xl font-black">CRM-connected measurement</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">Where the stack allows it, measurement can follow the path from ad click to website visit, lead, CRM record, sales opportunity, customer and revenue.</p><div className="mt-7 space-y-3 border-t border-border pt-6 text-sm font-semibold">{['HubSpot','Salesforce','Zoho','Pipedrive','Other supported CRM environments'].map(x=><div key={x} className="flex items-center gap-2"><Check className="size-4 text-brand"/>{x}</div>)}</div></div></div></div></section>

   <section className="border-y border-border bg-muted/30 py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><Heading label="Channel measurement" title="Your marketing channels should speak to the same business story.">GA4, advertising platforms, Search Console and your CRM answer different questions. A strong measurement framework defines how their signals relate without forcing every platform to report identical numbers.</Heading><div className="mt-14 grid gap-12 lg:grid-cols-2"><div><h3 className="text-2xl font-black">Paid advertising tracking</h3><div className="mt-6 divide-y divide-border border-y border-border">{[['Google Ads','Conversion actions, campaign context, UTMs and appropriate enhanced measurement approaches.'],['Meta','Pixel events and Conversions API where architecture, consent and platform capabilities support it.'],['TikTok','Browser events and supported Events API approaches where appropriate.'],['LinkedIn','Campaign and conversion signals for professional-audience advertising where applicable.'],['Other channels','Measurement can be evaluated for additional platforms when commercially relevant.']].map(([a,b])=><div key={a} className="py-5"><h4 className="font-black">{a}</h4><p className="mt-1 text-sm leading-6 text-muted-foreground">{b}</p></div>)}</div></div><div><h3 className="text-2xl font-black">E-commerce tracking</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">E-commerce measurement can connect product discovery with cart, checkout and purchase behavior, making it easier to investigate product performance and acquisition efficiency.</p><div className="mt-6 grid grid-cols-2 gap-3">{['Product views','Add to cart','Checkout','Purchases','Revenue','Quantity','Product IDs','Categories','Coupons','Refunds where supported','Funnel drop-off','Campaign performance'].map(x=><div key={x} className="border border-border bg-background p-4 text-sm font-semibold">{x}</div>)}</div></div></div></div></section>

   <section className="py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><div className="grid gap-16 lg:grid-cols-3"><div><MousePointerClick className="size-6 text-brand"/><h3 className="mt-6 text-2xl font-black">Forms & calls</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">Forms can be measured across views, starts, submissions and abandonment where feasible. Phone clicks can be tracked directly; full call-source measurement may require a call-tracking system.</p></div><div><Server className="size-6 text-brand"/><h3 className="mt-6 text-2xl font-black">Server-side measurement</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">Browser events, server-side events, conversion APIs, enhanced conversion concepts and first-party data can each play a role. The right architecture depends on platform support, consent and the technical environment.</p></div><div><ShieldCheck className="size-6 text-brand"/><h3 className="mt-6 text-2xl font-black">Privacy & consent</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">Tracking should account for consent behavior, data minimization, access controls and regional requirements. Legal compliance should be assessed with qualified advisers.</p></div></div><div className="mt-16 grid gap-px border border-border bg-border sm:grid-cols-2 lg:grid-cols-4">{[[ShieldCheck,'Consent management','Support consent-based tag behavior where required.'],[LockKeyhole,'Data minimization','Collect what is useful rather than everything imaginable.'],[Server,'First-party architecture','Use appropriate first-party signals where technically possible.'],[Settings2,'Access control','Keep measurement systems maintainable and responsibly administered.']].map(([I,a,b])=>{const Icon=I as typeof ShieldCheck;return <div key={a as string} className="bg-background p-6"><Icon className="size-5 text-brand"/><h4 className="mt-5 font-black">{a as string}</h4><p className="mt-2 text-sm leading-6 text-muted-foreground">{b as string}</p></div>})}</div></div></section>

   <section id="audit" className="border-y border-border bg-muted/30 py-20 lg:py-28"><div className="mx-auto grid max-w-7xl gap-14 px-5 sm:px-8 lg:grid-cols-12 lg:px-12"><div className="lg:col-span-5"><Heading label="Analytics audit" title="Find out whether your measurement can actually be trusted.">An analytics audit examines the implementation as a system, not a collection of isolated tags.</Heading><Link href="/contact" className="mt-8 inline-flex items-center gap-2 bg-brand px-6 py-3 text-sm font-bold text-white">Audit My Analytics <ArrowRight className="size-4"/></Link></div><div className="lg:col-span-7"><div className="grid gap-px border border-border bg-border sm:grid-cols-2">{[['Tracking','Are important events firing correctly?'],['Conversions','Are meaningful actions counted once and correctly?'],['Attribution','Can acquisition sources be interpreted consistently?'],['Tags','Are tags implemented, triggered and maintained correctly?'],['Website','Are important interactions measurable?'],['Ads','Are platforms receiving useful conversion signals?'],['CRM','Can leads be traced beyond the initial form?'],['Reporting','Do dashboards present information the business can trust?']].map(([a,b])=><div key={a} className="bg-background p-6"><p className="text-xs font-bold uppercase tracking-[.15em] text-brand">{a}</p><p className="mt-3 font-semibold leading-6">{b}</p></div>)}</div></div></div></section>

   <section className="py-20 lg:py-28"><div className="mx-auto grid max-w-7xl gap-14 px-5 sm:px-8 lg:grid-cols-12 lg:px-12"><div className="lg:col-span-5"><Heading label="Dashboards & reporting" title="Reports should answer questions, not just display numbers.">Useful reporting reduces the distance between a signal and a decision. The reporting layer may use GA4, Looker Studio, Search Console, advertising platforms, CRM information or custom reporting.</Heading></div><div className="lg:col-span-7"><div className="border border-border bg-slate-950 p-5 text-white"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-slate-500">Executive measurement view</p><p className="mt-1 font-bold">Marketing performance</p></div><span className="text-xs text-slate-400">Decision-ready view</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{[['Acquisition','Where users came from'],['Engagement','What they did'],['Conversion','What they completed'],['Revenue','What created value'],['Efficiency','What it cost'],['Trends','What is changing']].map(([a,b])=><div key={a} className="border border-white/10 bg-white/[.03] p-4"><p className="text-sm font-black">{a}</p><p className="mt-1 text-xs text-slate-500">{b}</p></div>)}</div><div className="mt-5 flex items-end gap-2 border-t border-white/10 pt-6" aria-hidden="true">{[35,50,43,62,56,73,67,82,76,90,84,96].map((h,i)=><div key={i} className="flex-1 bg-brand/70" style={{height:h}}/>)}</div></div></div></div></section>

   <section className="bg-slate-950 py-20 text-white lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><Label>Customer journey</Label><h2 className="mt-4 max-w-4xl text-4xl font-black tracking-tight sm:text-5xl">See the journey, not just the click.</h2><div className="mt-14 grid gap-3 md:grid-cols-7">{['Ad / Search / Social','Website visit','Content interaction','Lead / Cart','CRM','Sales','Customer / Repeat'].map((x,i)=><div key={x} className="border border-white/10 bg-white/[.03] p-5"><span className="font-mono text-xs text-brand">0{i+1}</span><p className="mt-5 text-sm font-bold">{x}</p></div>)}</div><p className="mt-10 max-w-3xl text-base leading-7 text-slate-400">Connecting stages provides deeper business intelligence and exposes where measurement stops, which is often where the most valuable questions begin.</p></div></section>

   <section className="py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><Heading label="Analytics across your ecosystem" title="One measurement layer should support the rest of your growth system.">Measurement can support the decisions made across search, paid media, websites, social, conversion optimization, email and automation.</Heading><div className="mt-14 divide-y divide-border border-y border-border">{[['SEO analytics','Organic traffic, landing pages, Search Console queries, impressions, clicks, CTR, conversion rate, organic leads and revenue.','/services/seo','Explore SEO'],['Paid media analytics','Campaign performance, conversion tracking, acquisition cost, revenue, ROAS, lead quality and attribution context.','/services/paid-media','Explore Paid Media'],['Social media analytics','Reach, engagement, clicks, website traffic, leads and content performance while separating platform metrics from business outcomes.','/services/social-media','Explore Social Media'],['Conversion analytics','Landing pages, CTA interactions, forms, checkout behavior, funnel drop-offs, devices and traffic-source performance.','/services/conversion-optimization','Explore Conversion Optimization']].map(([a,b,href,c])=><div key={a} className="grid gap-6 py-8 lg:grid-cols-[260px_1fr_220px] lg:items-center"><h3 className="text-xl font-black">{a}</h3><p className="text-sm leading-7 text-muted-foreground">{b}</p><ArrowLink href={href}>{c}</ArrowLink></div>)}</div><div className="mt-10 border-l-2 border-brand pl-5 text-sm leading-7 text-muted-foreground">Analytics tells us where friction or opportunity may exist. Conversion optimization uses those insights to test improvements rather than treating a single metric as the answer.</div></div></section>

   <section className="border-y border-border bg-muted/30 py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><div className="grid gap-14 lg:grid-cols-2"><div><Label>Next.js analytics</Label><h2 className="mt-4 text-4xl font-black tracking-tight">Modern JavaScript applications need deliberate measurement.</h2><p className="mt-6 leading-7 text-muted-foreground">Next.js does not automatically make analytics correct. Client-side events, route changes, dynamic pages, form interactions, ecommerce behavior, consent and server/client boundaries need deliberate handling.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{['Client-side events','Route changes','Dynamic pages','Form events','E-commerce interactions','Custom event architecture','GTM + GA4','Consent handling','Server-side events where appropriate','Performance considerations'].map(x=><div key={x} className="flex items-center gap-2 border border-border bg-background p-4 text-sm font-semibold"><Check className="size-4 text-brand"/>{x}</div>)}</div></div><div><Label>Website redesigns & migrations</Label><h2 className="mt-4 text-4xl font-black tracking-tight">Do not rebuild the website and lose the measurement layer.</h2><p className="mt-6 leading-7 text-muted-foreground">Analytics should be considered before launch. Existing properties, conversion definitions, UTMs, events, tags, redirects and reporting expectations should be inventoried and migrated deliberately.</p><div className="mt-8 border-y border-border">{['Existing measurement inventory','Conversion-definition review','UTM and campaign continuity','Analytics property preservation','Event and tag migration','Redirect and URL considerations','Pre-launch validation','Before/after comparison'].map((x,i)=><div key={x} className="flex gap-4 border-b border-border py-4 last:border-0 text-sm"><span className="font-mono text-xs text-brand">0{i+1}</span>{x}</div>)}</div><div className="mt-8"><ArrowLink href="/services/web-development">Explore Web Development</ArrowLink></div></div></div></div></section>

   <section className="py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><Heading label="Know what each system answers" title="GA4, Search Console, ad platforms and CRM data are not interchangeable.">Different systems observe different parts of the customer journey. A strong measurement framework respects those differences rather than expecting every platform to show identical totals.</Heading><div className="mt-14 grid gap-px border border-border bg-border md:grid-cols-4">{[['GA4','Website/app behavior','What did people do on the digital property?'],['Search Console','Organic search','How did the site appear and perform in search?'],['Ad platforms','Paid campaigns','How does this platform report campaign and conversion performance?'],['CRM','Sales lifecycle','Did the lead become an opportunity or customer?']].map(([a,b,c])=><div key={a} className="bg-background p-7"><p className="font-black">{a}</p><p className="mt-2 text-xs font-bold uppercase tracking-[.14em] text-brand">{b}</p><p className="mt-6 text-sm leading-6 text-muted-foreground">{c}</p></div>)}</div></div></section>

   <section className="bg-muted/30 py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><Heading label="Common mistakes" title="The analytics problems we look for first.">Good measurement is less about collecting more numbers and more about removing ambiguity from the numbers that influence decisions.</Heading><div className="mt-14 grid gap-x-10 md:grid-cols-2">{[['Installing analytics and never configuring it','A property can collect traffic while failing to answer business questions.'],['Tracking everything without a strategy','A large event list does not automatically produce useful insight.'],['Tracking vanity metrics','Reach, sessions or clicks should not replace meaningful outcomes.'],['Double-counting conversions','Duplicate tags and overlapping definitions distort performance.'],['Ignoring lead quality','A low cost per lead is not necessarily useful if leads do not become opportunities.'],['Inconsistent UTMs','Campaign reporting fragments when naming conventions change.'],['Not validating tags','Publishing a tag is only the beginning. Events and parameters need testing.'],['Ignoring consent','Tracking architecture should account for privacy choices.'],['Relying on one attribution model','Every model is a lens; none perfectly reconstructs the journey.'],['Not connecting CRM data','Form submissions can hide which marketing creates real value.'],['Ignoring offline conversions','Some businesses close sales outside the website.'],['Measuring traffic instead of outcomes','More visitors are not automatically more customers or revenue.']].map(([a,b],i)=><div key={a} className="border-b border-border py-7"><div className="flex gap-4"><span className="font-mono text-xs text-brand">{String(i+1).padStart(2,'0')}</span><div><h3 className="font-black">{a}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{b}</p></div></div></div>)}</div></div></section>

   <section className="py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><Heading label="Our approach" title="Measurement is infrastructure, not decoration.">The analytics layer should be understandable, maintainable and connected to how the business actually operates.</Heading><div className="grid gap-px border border-border bg-border sm:grid-cols-2">{[['Strategy first','Define what matters before implementing tracking.'],['Business-focused','Tie measurement to actual objectives and outcomes.'],['Technical','Engineer the implementation instead of relying on assumptions.'],['Privacy-aware','Respect consent, data minimization and applicable requirements.'],['Cross-channel','Connect website, advertising, SEO and CRM signals where practical.'],['Actionable','Turn reporting into decisions, priorities and tests.'],['Transparent','Document what is measured and why.'],['Maintainable','Use conventions, inventories and documentation that survive changes.']].map(([a,b])=><div key={a} className="bg-background p-6"><h3 className="font-black">{a}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{b}</p></div>)}</div></div></div></section>

   <section className="border-y border-border bg-slate-950 py-20 text-white lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><Label>How we work</Label><h2 className="mt-4 max-w-3xl text-4xl font-black tracking-tight sm:text-5xl">Eight stages from uncertainty to a usable measurement system.</h2><div className="mt-14 grid gap-px border border-white/10 bg-white/10 md:grid-cols-2 lg:grid-cols-4">{process.map(([n,a,b])=><div key={n} className="bg-slate-950 p-7"><span className="font-mono text-xs text-brand">{n}</span><h3 className="mt-6 text-lg font-black">{a}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{b}</p></div>)}</div><Link href="/contact" className="mt-10 inline-flex items-center gap-2 bg-brand px-6 py-3 text-sm font-bold text-white">Set Up My Analytics <ArrowRight className="size-4"/></Link></div></section>

   <section className="py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><div className="grid gap-12 lg:grid-cols-3"><div><ClipboardCheck className="size-6 text-brand"/><h3 className="mt-6 text-2xl font-black">QA & validation</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">Events, tags, conversions, parameters, UTMs, ecommerce, forms, advertising pixels, cross-domain behavior, consent and device journeys are tested as appropriate.</p></div><div><Workflow className="size-6 text-brand"/><h3 className="mt-6 text-2xl font-black">Deliverables</h3><ul className="mt-4 space-y-3 text-sm text-muted-foreground">{['Analytics audit','Measurement strategy','KPI framework','GA4 / GTM implementation','Event and conversion tracking','UTM framework','Advertising pixels','CRM integration','Ecommerce tracking','Dashboards and reporting','Data QA','Documentation'].map(x=><li key={x} className="flex gap-2"><Check className="mt-1 size-4 shrink-0 text-brand"/>{x}</li>)}</ul></div><div><FileSearch className="size-6 text-brand"/><h3 className="mt-6 text-2xl font-black">Documentation</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">Professional implementations should remain understandable after launch. Documentation can include a tracking plan, event dictionary, naming conventions, conversion definitions, tag inventory, UTM conventions, data-source mapping and dashboard definitions.</p></div></div></div></section>

   <section className="border-y border-border bg-muted/30 py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><Heading label="Technology ecosystem" title="The tools matter. The architecture matters more.">We work across the analytics, advertising, website and CRM layers that may contribute to a client’s measurement environment. Exact tools are selected around the project rather than presented as a wall of logos.</Heading><div className="mt-14 grid gap-px border border-border bg-border sm:grid-cols-2 lg:grid-cols-5">{[['GA4','Website and app behavior, events, conversions and audiences.'],['Google Tag Manager','A controlled layer for analytics and advertising tags.'],['Search Console','Organic search visibility, queries, impressions and clicks.'],['Looker Studio','Visual reporting when a reporting layer is appropriate.'],['Google Ads','Advertising conversion signals and campaign performance.'],['Meta','Pixel, events and Conversions API where appropriate.'],['TikTok','Event measurement and Events API capabilities where supported.'],['LinkedIn','Professional-audience campaign measurement where applicable.'],['CRM Systems','Lead, opportunity and customer information.'],['Next.js / React','Modern application measurement across routes and interactions.']].map(([a,b])=><div key={a} className="bg-background p-6"><p className="font-black">{a}</p><p className="mt-3 text-sm leading-6 text-muted-foreground">{b}</p></div>)}</div></div></section>

   <section className="py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><Heading label="Who benefits" title="Measurement changes with the business model.">The questions are different for an online store, B2B company, SaaS product and local service business. The measurement plan should reflect those differences.</Heading><div className="mt-14 grid gap-8 md:grid-cols-3">{[['E-commerce','Products, carts, checkout, purchases, revenue, product performance and acquisition efficiency.'],['Service businesses','Forms, calls, enquiries, bookings, lead sources and lead quality.'],['B2B','Leads, opportunities, sales stages and longer journeys.'],['SaaS','Signups, trials, activation and subscriptions.'],['Local businesses','Calls, enquiries, bookings, directions and local acquisition sources.'],['NGOs','Donations, volunteer actions, enquiries and engagement.'],['Education','Enquiries, applications, registrations and downloads.'],['Startups','A measurement foundation that can evolve with product and marketing.'],['Enterprise','Complex ecosystems requiring governance, integrations and reporting.']].map(([a,b])=><div key={a} className="border-t border-border pt-6"><h3 className="text-xl font-black">{a}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{b}</p></div>)}</div></div></section>

   <section className="border-y border-border bg-muted/30 py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><Heading label="Key metrics" title="Measure the layer of the business you actually need to manage.">Not every organization needs every metric. The right measurement set depends on the objective, business model, funnel and data availability.</Heading><div className="mt-14 grid gap-px border border-border bg-border md:grid-cols-4">{[['Acquisition',['Users','Sessions','Traffic sources','Campaigns']],['Engagement',['Engagement rate','Key events','Content interactions','Funnel activity']],['Conversion',['Leads','Purchases','Bookings','Signups']],['Revenue',['Revenue','Average order value','Customer acquisition cost','ROAS / LTV where available']]].map(([a,items])=><div key={a as string} className="bg-background p-7"><h3 className="font-black">{a as string}</h3><ul className="mt-5 space-y-3 text-sm text-muted-foreground">{(items as string[]).map(x=><li key={x} className="flex gap-2"><Check className="mt-1 size-4 shrink-0 text-brand"/>{x}</li>)}</ul></div>)}</div></div></section>

   <section className="bg-slate-950 py-20 text-white lg:py-28"><div className="mx-auto grid max-w-7xl gap-14 px-5 sm:px-8 lg:grid-cols-12 lg:px-12"><div className="lg:col-span-6"><Label>Engagement models</Label><h2 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">The scope depends on the complexity of your measurement ecosystem.</h2><p className="mt-6 leading-7 text-slate-400">We do not use a fixed price because a simple website audit and a multi-domain ecommerce, advertising and CRM implementation are materially different projects.</p></div><div className="lg:col-span-6"><div className="divide-y divide-white/10 border-y border-white/10">{[['One-time implementation','For businesses that need a structured analytics foundation.'],['Tracking audit','For teams that already have analytics but do not trust the implementation.'],['Migration project','For redesigns, platform changes and new measurement architectures.'],['Ongoing analytics support','For continued QA, reporting and measurement improvements.'],['Analytics consulting','For strategic guidance without a full implementation engagement.']].map(([a,b])=><div key={a} className="py-6"><h3 className="font-black">{a}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{b}</p></div>)}</div><p className="mt-7 text-xs leading-5 text-slate-500">Scope is influenced by website complexity, platforms, conversions, ecommerce, CRM integration, domains, server-side requirements, reporting needs and existing implementation quality.</p></div></div></section>

   <section id="faq" className="py-20 lg:py-28"><div className="mx-auto max-w-5xl px-5 sm:px-8 lg:px-12"><Heading label="Frequently asked questions" title="Answers to common analytics and tracking questions.">Clear definitions and direct answers help decision-makers and technical teams understand what the service involves.</Heading><div className="mt-14 border-y border-border">{faqs.map(([q,a])=><details key={q} className="group border-b border-border last:border-0"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 py-6 font-bold focus:outline-none focus-visible:ring-2 focus-visible:ring-brand focus-visible:ring-offset-4 [&::-webkit-details-marker]:hidden"><span>{q}</span><ChevronRight className="size-5 shrink-0 text-muted-foreground transition-transform group-open:rotate-90"/></summary><p className="max-w-3xl pb-6 pr-8 text-sm leading-7 text-muted-foreground">{a}</p></details>)}</div><Link href="/contact" className="mt-10 inline-flex items-center gap-2 bg-foreground px-6 py-3 text-sm font-bold text-background">Talk to an Analytics Specialist <ArrowRight className="size-4"/></Link></div></section>

   <section className="relative overflow-hidden bg-slate-950 py-24 text-white lg:py-32"><Image src="/images/hero-data.png" alt="Abstract digital data environment representing measurement and analytics" fill sizes="100vw" className="object-cover object-center opacity-25"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(2,6,23,.98)_0%,rgba(2,6,23,.72)_60%,rgba(2,6,23,.4)_100%)]"/><div className="relative mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><div className="max-w-3xl"><Label>Your data should tell you what to do next.</Label><h2 className="mt-5 text-4xl font-black tracking-[-.04em] sm:text-5xl lg:text-7xl">Stop guessing where your marketing is working.</h2><p className="mt-7 max-w-2xl text-base leading-7 text-slate-300 sm:text-lg">Whether the problem is broken tracking, unclear attribution, unreliable conversions, missing CRM visibility or a reporting system nobody trusts, we can start by understanding the measurement gap.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/contact" className="inline-flex items-center justify-center gap-2 bg-brand px-7 py-4 text-sm font-bold text-white hover:bg-brand/90">Build My Measurement System <ArrowRight className="size-4"/></Link><Link href="/contact" className="inline-flex items-center justify-center gap-2 border border-white/20 bg-white/5 px-7 py-4 text-sm font-bold text-white hover:bg-white/10">Book a Consultation</Link></div></div></div></section>
  </main>
 </>
}
